language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install systemd-python

# command to run tests
script:
  - flask run &
  - tox