language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install tox
  - pip3 install tox-travis
  - pip3 install coverage
  - pip3 install bs4
# command to run tests
script:
  - tox